### ISSUE TITLE
Torrents do not show when added from outside the web-ui

### ISSUE THREAD

**Issue by dipspit** [Secretmapper/combustion#10]
Torrents do not show when added outside the web-ui. For example: If I add a torrent using Transmission Remote GUI on Mac it does not appear, it appears only torrents added using the web-ui itself will show.

**Comment by Secretmapper** [comment]
Hmmm. That's weird, the client rechecks every 5 seconds from the server for new torrents added. I'll try to replicate it.

**Comment by tr1plus** [comment]
For me this works. I have services adding torrents and they show up in the web ui

**Comment by dipspit** [comment]
I have it running on a Raspi. The amount of torrents shows up, the up/down speed shows up, but the torrents themselves don't appear. On mobile or desktop Safari.

**Comment by mbazdell** [comment]
I'm having a similar issue, possibly the same, on 2.84-0.2 on Raspbian. I used the web/ replacement method. Switched back to the default interface and everything is there. I'm using Transmission behind a reverse proxy with Nginx. I get a 405 error for the RPC call ever 5 seconds.

**Comment by vergessen** [comment]
I believe this is an issue with Mobile safari and combustion.  I have noticed that on my ipad/iphone nothing already in transmission shows up.

**Comment by mbazdell** [comment]
I was able to resolve this by editing where it's hardcoded to </transmission/rpc/> in the main.*.js file.

In vim
:%s /transmission\/rpc/rpc/gc

Works fine now.

**Comment by Secretmapper** [comment]
This seems to be a configuration issue on the server. The web client is interacting with the RPC the same way the default transmission client does.

Closing for now, but, please comment if the problem persists

**Comment by Taluu** [comment]
Bumping this issue, as I also had the problem. The `sed` solved it. IMO, this is an issue with building the release, as in the release, `transmission/rpc/` is hardcoded... so, it doesn't seem to be a server issue.

On my server, I chose to use nginx and a proxy-pass, with `/rpc` redirecting to transmission's rpc url :

```
    location /rpc {
        proxy_pass         http://127.0.0.1:9091/transmission/rpc;
    }
```

Couldn't using an env var or something allow to tinker that bit ?

**Comment by Secretmapper** [comment]
Ah,

**Comment by Secretmapper** [comment]
Added to latest release!
