### ISSUE TITLE
Torrent doesn't show up in Safari

### ISSUE THREAD

**Issue by andyts93** [Secretmapper/combustion#12]
Using Safari on mobile or desktop I can't view the list of torrent

**Safari Mobile**
![transmission-iphone-7](https://cloud.githubusercontent.com/assets/4661039/24998825/b7d0bb9a-203b-11e7-80cf-8f43a9b638ef.jpg)

**Chrome desktop in mobile view**
![trasmissione-chrome](https://cloud.githubusercontent.com/assets/4661039/24998790/9c9a9b5c-203b-11e7-9e59-4e970e2a75f4.jpg)

**Comment by Secretmapper** [comment]
Thanks for the find. Will look into this in the weekend.

**Comment by Harry-Harrison** [comment]
I also have this issue on desktop and mobile with Safari. 

`[Error] Failed to load resource: the server responded with a status of 409 (Conflict) (rpc, line 0)`

**Comment by Secretmapper** [comment]
@Harry-Harrison the error is normal. The rpc always fails on it's first request and transmission will then assign a token for subsequent requests. The same error appears on the default theme. However, thanks for bringing it up, as it made me realize I should suppress the error for good measure.

I checked it a bit a while ago and it seems to be a CSS-only bug (the list/data are there but they're somehow invisible)

**Comment by Harry-Harrison** [comment]
Taking the `overflow-y: scroll;` off of `index__main` seems to fix this.

**Comment by Secretmapper** [comment]
@Harry-Harrison Awesome, thanks! 556e93062c59e16b73a006e014bdda96d1b60092
