### ISSUE TITLE
Settings not showing up in UI

### ISSUE THREAD

**Issue by tr1plus** [Secretmapper/combustion#16]
When going to the UI, it seems none of the settings that are defined in the settings.json are visible. Everything is empty for me in the ui, while there is configuration done in the file (which is also working, as my downloads are going to the correct folder, download limit is okay, ...).

I just re downloaded the latest release to check but same result. 

Kind regards
Joren C

**Comment by dembala** [comment]
Same for me. Settings in Combustion shows everything empty, not filled or off. As if it wasn't reading out the values. I am running transmission on a synology box.

**Comment by Secretmapper** [comment]
Would it be possible to know what browser versions you are using? I tested it on Safari, Chrome, and Firefox, and they all seem to work.

**Comment by Secretmapper** [comment]
I can't replicate this issue, so I'm closing it for now. If anyone can take a screenshot and provide the environment where this is present, that would be a big help.

**Comment by dembala** [comment]
Environment: Synology DS 213j running fw DSM 6.1.3-15152 (latest at this timestamp).
Transmission 2.92-12 (Diaoul - SynoCommunity).
As you can see in below screenshots settings of the transmission box are not reflected here, although i obviously have a Download dir configured and "start when added" is enabled and so on.

![torrents](https://user-images.githubusercontent.com/16404689/30219912-e20b0018-94bd-11e7-866e-c09084ec5002.PNG)
![speed](https://user-images.githubusercontent.com/16404689/30219916-e5d8789c-94bd-11e7-9ade-b890251e1f6f.PNG)

**Comment by shady2k** [comment]
Same error here. Original gui has Authorization header. And your gui not and it have 401 error in rpc request Payload {method: "session-get"}.
