### ISSUE TITLE
Icon issue

### ISSUE THREAD

**Issue by dembala** [Secretmapper/combustion#17]
Lower left corner icon acts weird in safari on iPad. Not sure what that triangle icon should do anyway but if I press on it, it changes a bit, as if there was some grafix not fitting into that triangle shape, but nothing further happens. Pressing on it again makes the artifacts on the icon disappear again.

**Comment by Secretmapper** [comment]
That's weird. I tried it out on iPad (11.3 Beta) Safari, and it doesn't have this issue.

For reference, the triangle icon triggers rate limiting (turtle icon on old transmission). I'm using Material icons, and unfortunately there's no turtle icon there 😄. So I went with 'network' icon (triangle is the signal bar). This is a common source of confusion that I will look into remedying it, possibly with a text label.

**Comment by dembala** [comment]
I'm on 10.3.3. Ipad Air 2.

Bad icon lower left corner
![bad](https://user-images.githubusercontent.com/16404689/30219489-7797d752-94bc-11e7-8649-bd6ecf30316e.png)

Good icon lower left corner
![good](https://user-images.githubusercontent.com/16404689/30219517-90cb8b6a-94bc-11e7-8c44-4c14392e8226.png)

**Comment by Xiretza** [comment]
I'm pretty sure that's how it's supposed to look. The "good" one is a reception indicator (or in this case speed), the "bad" one is the same, but with an exclamation mark (meaning alternative download/upload speed limits are enabled).

**Comment by dembala** [comment]
:)  I couldn't figure that this is an exclamation mark. Now i really see that. Indeed. I thought it's something expanding to the right out of the triangle and i can't see the rest of it. Now i see what you mean indeed. Oh boy...   thanks!! :)

**Comment by Secretmapper** [comment]
Glad to hear!  Cheers!
