### ISSUE TITLE
Release up to date?

### ISSUE THREAD

**Issue by Cholaloula** [Secretmapper/combustion#18]
Hello, Just let you know I'm not really into code, I just can use SSH, guess things, and try to learn before asking, but after installing the theme in a manual way, I had the problem of the progress bar not displaying in percentage, or event the title saying "Combustion - Transmission ...".

Seeing the percentage issue as been solved, I was wondering how can I use the files available in this github to have an up-to-date version?

PS: Don't know if really an issue or me that can't use github, but daaaamn, this theme is great!!

Also don't know if it's because of my version or it's in a todo thing, but when making rightclick on a torrent I just have the "resume now" option, not the other ones, (remove, etc.).

Anyway, BIG thank you!!!!

Kind regards

**Comment by Secretmapper** [comment]
Hello @Cholaloula, thanks for the kind words!

You can always get the most recent version through (https://github.com/Secretmapper/combustion/archive/release.zip).

There should also be a notification system in place that checks if there's a new version (in app).

Hope that helps!

Closing this for now but please open/comment if you have nay problems!

**Comment by Secretmapper** [comment]
You are right RE: right clicking! The thing was/is, I want to remove right clicking (as all actions are available at the top).

The only one not yet available is resume now, and that's why it's the only one I kept. I'm still coming up of a way to add that in.
