### ISSUE TITLE
Bad docker documentation + docker version not working as expected

### ISSUE THREAD

**Issue by jribal** [Secretmapper/combustion#22]
Hi, I found an error in the readme.
this can't work : `sudo docker run -d --restart=always -p 80:80 --link some-transmission container combustion`
this does : `sudo docker run -d --restart=always -p 80:80 --link some-transmission combustion` 

In the Dockerfile I could find no trace of any link to transmission. The container starts on the webui but does not connect to transmission rpc. It tries to connect to the same adress.

my transmission docker is at : `mymachine:9091`
I've setup combustion to `machine:9093` and when I enter the website I can see the new interface and in console log failure to reach `mymachine:9093/transmission/rpc`

Anybody had success with the docker version ?

**Comment by Secretmapper** [comment]
The docker build is submitted via Pull Request (and I haven't tested it). I'll look into it. I'm collapsing this issue and making (#20) the official issue
