### ISSUE TITLE
Can't add a torrent

### ISSUE THREAD

**Issue by evanre** [Secretmapper/combustion#23]
Hi, I can not add a new torrent. I open the dialog, attach a .torrent file (or insert a magnet link) and click Ok. But nothing happens. New torrent isn't appearing in torrents list.

With Default UI everything fine.

p.s. I've also tried original [react UI](https://github.com/fcsonline/react-transmission) implementation. And there was the same problem

**Comment by Secretmapper** [comment]
Hmm, that's a weird. Does the original transmision web UI work? Would you be able to send the file so I can test? You can put it here or DM on twitter (same username)

**Comment by evanre** [comment]
Hi, @Secretmapper. Sorry I can't provide any files for you since this issue is no more relevant for me. Only reason I was searching for another UI's is that I couldn't manage torrents in default UI from touch devices. But I've found great android Transmission client and it solved the problem.

**Comment by Secretmapper** [comment]
Cheers!
